image: java:8

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - backend
  script:
    - chmod +x gradlew
    - ./gradlew bootJar
  artifacts:
    expire_in: 1 week
    paths:
      - build/libs/*.jar

deploy:
  variables:
    TAG: $CI_COMMIT_REF_SLUG
  stage: deploy
  tags:
    - deploy220
  script:
    - cp build/libs/*.jar docker
    - cd docker
    - docker stop side-project
    - docker build -t side-project:"$TAG" .
    - docker run -d --rm --name side-project -p 8080:8080 side-project:"$TAG"
  dependencies:
    - build