image: java:8

stages:
  - build
  - deploy

before_script:
  - chmod +x gradlew

build:
  stage: build
  tags:
    - backend
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - target/sideproject.jar

deploy:
  stage: deploy
  script:
    - java -jar target/sideproject.jar
# production:
#   stage: deploy
#   script:
#   - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
#   - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
#   - ./cf push
#   only:
#   - master