image: java:8

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - backend
  script:
    - chmod +x gradlew
    - ./gradlew bootJar
  artifacts:
    expire_in: 1 week
    paths:
      - build/libs/*.jar

deploy:
  stage: deploy
  tags:
    - deploy220
  script:
    - cp build/libs/*.jar docker
    - cd docker
    - docker stop side-project || true
    - docker rmi side-project:$CI_COMMIT_REF_SLUG || true
    - docker build -t side-project:$CI_COMMIT_REF_SLUG .
    - docker run -d --rm --name side-project -p 8080:8080 side-project:$CI_COMMIT_REF_SLUG
#  dependencies:
#    - build